pub const HIDE_STRINGS: &[Option<&str>] = &[
    Some("The data in Networksolutions.com's WHOIS database"), None,
    Some("TERMS OF USE: You are not authorized"), None,
    Some("The data in Register.com's WHOIS database"), None,
    Some("The Data in the Tucows Registrar WHOIS database"), None,
    Some("TERMS OF USE: The Data in Gabia' WHOIS"), None,
    Some("The data contained in GoDaddy.com"), None,
    Some("Personal data access and use are governed by French"), None,
    Some("The data in this whois database is provided to you"), None,
    Some("Please register your domains at; http://www."), None,
    Some("%% NOTICE: Access to this information is provided"), None,
    Some("NOTICE: Access to the domain name's information"), None,
    Some("NOTICE: The expiration date"), None,

    Some("The Data in MarkMonitor.com's"), None,
    Some("Corporation Service Company(c) (CSC)  The Trusted Partner"), Some("Register your domain name at"),
    Some("The data in Networksolutions.com's"), None,
    Some("# Welcome to the OVH WHOIS Server"), Some(""),
    Some("TERMS OF USE OF MELBOURNE IT WHOIS DATABASE"), None,
    Some("The data contained in this Registrar's Whois"), None,
    Some("The data in the FastDomain Inc. WHOIS database"), None,
    Some("Access to WHOIS information is provided"), None,
    Some("This Registry database contains ONLY .EDU"), Some("domain names."),
    Some("Access to AFILIAS WHOIS information is provided"), None,
    Some("Access to Public Interest Registry WHOIS information"), None,
    Some("Telnames Limited, the Registry Operator for"), None,
    Some("Tralliance, Inc., the Registry Operator for .travel"), None,
    Some("The data in this record is provided by"), None,
    Some("Terms of Use: Donuts Inc. provides"), None,
    Some("Access to WHOIS information is provided"), None,
    Some("TERMS OF USE: You  are  not  authorized"), None,
    Some("The Whois and RDAP services are provided by CentralNic"), Some(""),
    Some(".Club Domains, LLC, the Registry Operator"), None,
    Some("% Except for agreed Internet operational purposes"), None,
    Some("TERMS OF USE: The information in the Whois database"), None,
    Some("The WHOIS service offered by Neustar, Inc, on behalf"), None,
    Some("The WHOIS service offered by the Registry Operator"), None,
    Some("Access to CCTLD WHOIS information is provided"), Some(""),
    Some("This WHOIS information is provided"), None,
    Some("% The WHOIS service offered by DNS Belgium"), Some(""),
    Some(".CO Internet, S.A.S., the Administrator"), None,
    Some("%  *The information provided"), Some("% https://www.nic.cr/iniciar-sesion/?next=/mi-cuenta/"),
    Some("% The WHOIS service offered by EURid"), Some("% of the database"),
    Some("Access to .IN WHOIS information"), None,
    Some("access to .in whois information"), None,
    Some("% Use of CIRA's WHOIS service is governed by the Terms of Use in its Legal"), None,
    Some("The Service is provided so that you may look"), Some("We may discontinue"),
    Some("NeuStar, Inc., the Registry Administrator for .US"), None,
    Some("Web-based WHOIS"), None,
    Some("If you wish"), None,
    Some("For more information on Whois"), None,
    Some("If you have"), None,
    Some("The data in"), None,
None, None
];
